nodeSelector:
  workload: system
tolerations:
  - key: CriticalAddonsOnly
    operator: Equal
    value: "true"
    effect: NoSchedule
replicas: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
