replicas: 2
serviceAccount:
  name: karpenter
settings:
  clusterName: ${CLUSTER_NAME}
  interruptionQueue: ${KARPENTER_INTERRUPTION_QUEUE}
controller:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1Gi
tolerations:
  - key: CriticalAddonsOnly
    operator: Equal
    value: "true"
    effect: NoSchedule
nodeSelector:
  workload: system
podDisruptionBudget:
  name: karpenter
  maxUnavailable: 1
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: karpenter
